version: 1.0.{build}
image:
- Visual Studio 2015
- ubuntu1804

for:
-
  matrix:
    only:
      - image: ubuntu1804

  build_script:
  - sudo apt-get install build-essential
  - cd "enet server test"
  - cd "enet2"
  - cmake CMakeLists.txt
  - make
  - cp libenet.a ../libenet.a
  - cd ..
  - g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote.
